#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_clean_setup () {
	ynh_clean_check_starting
}
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
is_public=$YNH_APP_ARG_IS_PUBLIC
language=$YNH_APP_ARG_LANGUAGE
admin=$YNH_APP_ARG_ADMIN
coop_name=$YNH_APP_ARG_COOP_NAME
street_address="$YNH_APP_ARG_STREET_ADDRESS"
zip_code=$YNH_APP_ARG_ZIP_CODE
city=$YNH_APP_ARG_CITY
country=$YNH_APP_ARG_COUNTRY
contact_email=$YNH_APP_ARG_CONTACT_EMAIL
contact_number=$YNH_APP_ARG_CONTACT_NUMBER
timezone=$YNH_APP_ARG_TIMEZONE
price_markup=$YNH_APP_ARG_PRICE_MARKUP
tax_vat_percentage=$YNH_APP_ARG_TAX_VAT_PERCENTAGE
use_wiki_plugin=$YNH_APP_ARG_USE_WIKI_PLUGIN
use_messages_plugin=$YNH_APP_ARG_USE_MESSAGES_PLUGIN
notification_reply_email=$YNH_APP_ARG_NOTIFICATION_REPLY_EMAIL
notification_sender_email=$YNH_APP_ARG_NOTIFICATION_SENDER_EMAIL
admin_email=$YNH_APP_ARG_ADMIN_EMAIL
smtp_domain=$YNH_APP_ARG_SMTP_DOMAIN

app=$YNH_APP_INSTANCE_NAME

secret_key_base=$(ynh_string_random 128)

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
ynh_script_progression --message="Validating installation parameters..."

final_path=/var/www/$app
test ! -e "$final_path" || ynh_die --message="This path already contains a folder"

# Register (book) web path
ynh_webpath_register --app=$app --domain=$domain --path_url=$path_url

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Storing installation settings..." --weight=3

ynh_app_setting_set --app=$app --key=domain --value=$domain
ynh_app_setting_set --app=$app --key=path --value=$path_url
ynh_app_setting_set --app=$app --key=language --value=$language
ynh_app_setting_set --app=$app --key=admin --value=$admin
ynh_app_setting_set --app=$app --key=coop_name --value=$coop_name
ynh_app_setting_set --app=$app --key=street_address --value="$street_address"
ynh_app_setting_set --app=$app --key=zip_code --value=$zip_code
ynh_app_setting_set --app=$app --key=city --value=$city
ynh_app_setting_set --app=$app --key=country --value=$country
ynh_app_setting_set --app=$app --key=contact_email --value=$contact_email
ynh_app_setting_set --app=$app --key=contact_number --value=$contact_number
ynh_app_setting_set --app=$app --key=timezone --value=$timezone
ynh_app_setting_set --app=$app --key=price_markup --value=$price_markup
ynh_app_setting_set --app=$app --key=tax_vat_percentage --value=$tax_vat_percentage
ynh_app_setting_set --app=$app --key=use_wiki_plugin --value=$use_wiki_plugin
ynh_app_setting_set --app=$app --key=use_messages_plugin --value=$use_messages_plugin
ynh_app_setting_set --app=$app --key=notification_sender_email --value=$notification_sender_email
ynh_app_setting_set --app=$app --key=notification_reply_email --value=$notification_reply_email
ynh_app_setting_set --app=$app --key=admin_email --value=$admin_email
ynh_app_setting_set --app=$app --key=smtp_domain --value=$smtp_domain
ynh_app_setting_set --app=$app --key=secret_key_base --value=$secret_key_base

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN A PORT
#=================================================
ynh_script_progression --message="Finding an available port..." --weight=2

# Find an available port
port=$(ynh_find_port --port=8095)
ynh_app_setting_set --app=$app --key=port --value=$port

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..." --weight=15

ynh_install_app_dependencies $pkg_dependencies $build_pkg_dependencies
ynh_install_ruby --ruby_version=$ruby_version
ynh_install_extra_app_dependencies --repo="deb https://dl.yarnpkg.com/debian/ stable main" --package="yarn" --key="https://dl.yarnpkg.com/debian/pubkey.gpg"

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression --message="Configuring system user..." --weight=3

# Create a system user
ynh_system_user_create --username=$app --home_dir="$final_path"

#=================================================
# CREATE A MYSQL DATABASE
#=================================================
ynh_script_progression --message="Creating a MySQL database..." --weight=1

db_name=$(ynh_sanitize_dbid --db_name=$app)
db_user=$db_name
ynh_app_setting_set --app=$app --key=db_name --value=$db_name
ynh_mysql_setup_db --db_user=$db_user --db_name=$db_name
db_pwd=$(ynh_app_setting_get --app=$app --key=mysqlpwd)

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

ynh_app_setting_set --app=$app --key=final_path --value=$final_path
# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$final_path"

chmod 750 "$final_path"
chmod -R o-rwx "$final_path"
chown -R $app:$app "$final_path"

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=1

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SPECIFIC SETUP
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=10

# Note(decentral1se): Handle YAML truthiness
if [ $use_wiki_plugin = 0 ]; then
  use_wiki_plugin="False"
else
  use_wiki_plugin="True"
fi

# Note(decentral1se): Handle YAML truthiness
if [ $use_messages_plugin = 0 ]; then
  use_messages_plugin="False"
else
  use_messages_plugin="True"
fi

ynh_add_config --template="../conf/app_config.yml" --destination="$final_path/config/app_config.yml"
ynh_add_config --template="../conf/storage.yml" --destination="$final_path/config/storage.yml"

queue_name=$app
smtp_domain=$smtp_domain
smtp_address=$app@$smtp_domain
smtp_port=25
smtp_user_name=$app

# TODO(decentral1se): figure out what to do here
smtp_password=__TODO__

redis_url="redis://localhost:6379"

ynh_app_setting_set --app=$app --key=queue_name --value=$queue_name

ynh_add_config --template="../conf/foodsoft.env" --destination="$final_path/foodsoft.env"
ynh_add_config --template="../conf/resque.env" --destination="$final_path/resque.env"

#=================================================
# INSTALL APPLICATION DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing Ruby $ruby_version dependencies..." --weight=50

ynh_use_ruby

pushd $final_path
  gem install --no-document bundler -v "~> 1"
  gem install --no-document passenger -v "~> 6"
  bundle config build.nokogiri "--use-system-libraries"
  bundle install --deployment --without development test -j 4
popd

ynh_install_app_dependencies $pkg_dependencies

#=================================================
# RUN DATABASE SETUP AND MIGRATION WITH ROOT USER
#=================================================
ynh_script_progression --message="Initialising the database..." --weight=20

ynh_add_config --template="../conf/db_setup.yml" --destination="$final_path/config/database.yml"
pushd $final_path
  bundle exec rake db:setup RAILS_ENV=production SECRET_KEY_BASE=$secret_key_base
popd

#=================================================
# RUN DATABASE MIGRATION WITH APPLICATION USER
#=================================================
ynh_script_progression --message="Migrating the database..." --weight=10

ynh_add_config --template="../conf/db_prod.yml" --destination="$final_path/config/database.yml"
pushd $final_path
  bundle exec rake db:migrate RAILS_ENV=production SECRET_KEY_BASE=$secret_key_base
popd

#=================================================
# SETUP ADMINSTRATOR ACCOUNT
#=================================================
ynh_script_progression --message="Setting up the adminstrator account..." --weight=4

admin_first_name=$(ynh_user_get_info --username=$admin --key=firstname)
admin_last_name=$(ynh_user_get_info --username=$admin --key=lastname)
admin_email=$(ynh_user_get_info --username=$admin --key=mail)

# Note(decentral1se): figure out how to update the password and salt. Not sure which to use
# root@ynhdev-decentral1-se:~# mysql -u root -e "connect foodsoft; select * from users where nick = 'admin'"
# +----+--------------+------------------------------------------+--------------- ...
# | id | nick         | password_hash                            | password_salt  ...
# +----+--------------+------------------------------------------+--------------- ...
# |  1 | admin        | 7a2fe6291c632523300b8ab4ac70559ea0b706fa | g/6muzHs       ...
# +----+--------------+------------------------------------------+--------------- ...

ynh_mysql_execute_as_root --sql="update users set first_name = '$admin_first_name' where id = '1';" --database=$app
ynh_mysql_execute_as_root --sql="update users set last_name = '$admin_last_name' where id = '1';" --database=$app
ynh_mysql_execute_as_root --sql="update users set email = '$admin_email' where id = '1';" --database=$app
ynh_mysql_execute_as_root --sql="update users set nick = '$admin' where id = '1';" --database=$app

#=================================================
# PRE-COMPILE ASSETS
#=================================================
ynh_script_progression --message="Pre-compiling application assets..." --weight=40

pushd $final_path
  bundle exec rake assets:precompile RAILS_ENV=production SECRET_KEY_BASE=$secret_key_base
popd

chmod 750 "$final_path"
chmod -R o-rwx "$final_path"
chown -R $app:$app "$final_path"

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring a systemd service..." --weight=1

ynh_add_systemd_config --service=$app --template=foodsoft.service
ynh_add_systemd_config --service=resque  --template=resque.service

#=================================================
# GENERIC FINALIZATION
#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression --message="Configuring log rotation..." --weight=1

# Use logrotate to manage application logfile(s)
ynh_use_logrotate --logfile=$final_path/log/passenger.$port.log
ynh_use_logrotate --logfile=$final_path/log/production.log

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..." --weight=1

yunohost service add $app --description "$app daemon" --log=$final_path/log/passenger.$port.log
yunohost service add resque --description "resque daemon" --log=$final_path/log/production.log

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=5

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="$final_path/log/passenger.$port.log" --line_match="Passenger core online"
ynh_systemd_action --service_name=resque --action="start" --log_path=systemd --line_match="Started"

#=================================================
# SETUP SSOWAT
#=================================================
ynh_script_progression --message="Configuring permissions..." --weight=1

# Make app public if necessary
if [ $is_public -eq 1 ]
then
	# Everyone can access the app.
	# The "main" permission is automatically created before the install script.
	ynh_permission_update --permission="main" --add="visitors"
fi

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading NGINX web server..." --weight=1

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Installation of $app completed" --last
