#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================
ynh_script_progression --message="Validating installation parameters..." --weight=1

domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
is_public=$YNH_APP_ARG_IS_PUBLIC
language=$YNH_APP_ARG_LANGUAGE
app=$YNH_APP_INSTANCE_NAME
coop_name=$YNH_APP_ARG_COOP_NAME
street_address="$YNH_APP_ARG_STREET_ADDRESS"
zip_code=$YNH_APP_ARG_ZIP_CODE
city=$YNH_APP_ARG_CITY
country=$YNH_APP_ARG_COUNTRY
contact_email=$YNH_APP_ARG_CONTACT_EMAIL
contact_number=$YNH_APP_ARG_CONTACT_NUMBER
timezone=$YNH_APP_ARG_TIMEZONE
price_markup=$YNH_APP_ARG_PRICE_MARKUP
tax_vat_percentage=$YNH_APP_ARG_TAX_VAT_PERCENTAGE
use_wiki_plugin=$YNH_APP_ARG_USE_WIKI_PLUGIN
use_messages_plugin=$YNH_APP_ARG_USE_MESSAGES_PLUGIN
notification_reply_email=$YNH_APP_ARG_NOTIFICATION_REPLY_EMAIL
notification_sender_email=$YNH_APP_ARG_NOTIFICATION_SENDER_EMAIL
admin_email=$YNH_APP_ARG_ADMIN_EMAIL
smtp_domain=$YNH_APP_ARG_SMTP_DOMAIN

#=================================================
# VALIDATE AND REGISTER $FINAL_PATH
#=================================================
final_path=/var/www/$app

test ! -e "$final_path" || ynh_die --message="This path already contains a folder"

ynh_webpath_register --app=$app --domain=$domain --path_url=$path_url

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Storing installation settings..." --weight=3

ynh_app_setting_set --app=$app --key=domain --value=$domain
ynh_app_setting_set --app=$app --key=path --value=$path_url
ynh_app_setting_set --app=$app --key=admin --value=$admin
ynh_app_setting_set --app=$app --key=is_public --value=$is_public
ynh_app_setting_set --app=$app --key=language --value=$language
ynh_app_setting_set --app=$app --key=coop_name --value=$coop_name
ynh_app_setting_set --app=$app --key=street_address --value="$street_address"
ynh_app_setting_set --app=$app --key=zip_code --value=$zip_code
ynh_app_setting_set --app=$app --key=city --value=$city
ynh_app_setting_set --app=$app --key=country --value=$country
ynh_app_setting_set --app=$app --key=contact_email --value=$contact_email
ynh_app_setting_set --app=$app --key=contact_number --value=$contact_number
ynh_app_setting_set --app=$app --key=timezone --value=$timezone
ynh_app_setting_set --app=$app --key=price_markup --value=$price_markup
ynh_app_setting_set --app=$app --key=tax_vat_percentage --value=$tax_vat_percentage
ynh_app_setting_set --app=$app --key=use_wiki_plugin --value=$use_wiki_plugin
ynh_app_setting_set --app=$app --key=use_messages_plugin --value=$use_messages_plugin
ynh_app_setting_set --app=$app --key=notification_sender_email --value=$notification_sender_email
ynh_app_setting_set --app=$app --key=notification_reply_email --value=$notification_reply_email
ynh_app_setting_set --app=$app --key=admin_email --value=$admin_email
ynh_app_setting_set --app=$app --key=final_path --value=$final_path
ynh_app_setting_set --app=$app --key=smtp_domain --value=$smtp_domain

#=================================================
# INSTALL SYSTEM DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing system dependencies..." --weight=15

ynh_install_app_dependencies $pkg_dependencies

#=================================================
# CREATE A MYSQL DATABASE
#=================================================
ynh_script_progression --message="Creating a MySQL database..." --weight=1

db_name=$(ynh_sanitize_dbid --db_name=$app)
db_user=$db_name

ynh_app_setting_set --app=$app --key=db_name --value=$db_name
ynh_app_setting_set --app=$app --key=db_user --value=$db_user

ynh_mysql_setup_db --db_user=$db_user --db_name=$db_name

#=================================================
# SETUP APPLICATION SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

ynh_setup_source --dest_dir="$final_path"

#=================================================
# INSTALL RUBY
#=================================================
ynh_script_progression --message="Installing Ruby $ruby_version..." --weight=50

ynh_app_setting_set --app=$app --key=ruby_version --value=$ruby_version

ynh_package_remove $pkgs_to_remove

ynh_install_ruby $ruby_version

#=================================================
# FIND A FREE PORT
#=================================================
ynh_script_progression --message="Finding a free port..." --weight=2

port=$(ynh_find_port --port=3000)

ynh_app_setting_set --app=$app --key=port --value=$port

#=================================================
# GENERATE CONFIGURATION SECRETS
#=================================================
ynh_script_progression --message="Generating configuration secrets..." --weight=1

secret_key_base=$(ynh_string_random 128)

ynh_app_setting_set --app=$app --key=secret_key_base --value=$secret_key_base

#=================================================
# SETUP LOG FILES LOCATION
#=================================================
ynh_script_progression --message="Configuring log file location..." --weight=1

passenger_log_file=$final_path/log/passener.$port.log
prod_log_file=$final_path/log/production.log

ynh_app_setting_set --app=$app --key=resque_log_file --value=$prod_log_file
ynh_app_setting_set --app=$app --key=resque_log_file --value=$passenger_log_file

#=================================================
# SETUP APPLICATION CONFIGURATION 
#=================================================
ynh_script_progression --message="Configuring the application..." --weight=10

cp ../conf/app_config.yml $final_path/config/app_config.yml

ynh_replace_string --match_string="__NAME__" --replace_string=$coop_name --target_file=$final_path/config/app_config.yml
ynh_replace_string --match_string="__STREET_ADDRESS__" --replace_string="$street_address" --target_file=$final_path/config/app_config.yml
ynh_replace_string --match_string="__ZIP_CODE__" --replace_string=$zip_code --target_file=$final_path/config/app_config.yml
ynh_replace_string --match_string="__CITY__" --replace_string=$city --target_file=$final_path/config/app_config.yml
ynh_replace_string --match_string="__COUNTRY__" --replace_string=$country --target_file=$final_path/config/app_config.yml
ynh_replace_string --match_string="__CONTACT_EMAIL__" --replace_string=$contact_email --target_file=$final_path/config/app_config.yml
ynh_replace_string --match_string="__CONTACT_NUMBER__" --replace_string=$contact_number --target_file=$final_path/config/app_config.yml
ynh_replace_string --match_string="__DOMAIN__" --replace_string=$domain --target_file=$final_path/config/app_config.yml
ynh_replace_string --match_string="__PATH__" --replace_string=$path_url --target_file=$final_path/config/app_config.yml
ynh_replace_string --match_string="__LOCALE__" --replace_string=$language --target_file=$final_path/config/app_config.yml
ynh_replace_string --match_string="__PRICE_MARKUP__" --replace_string=$price_markup --target_file=$final_path/config/app_config.yml
ynh_replace_string --match_string="__TAX_VAT_PERCENTAGE__" --replace_string=$tax_vat_percentage --target_file=$final_path/config/app_config.yml

# Note(decentral1se): Handle YAML truthiness
if [ $use_wiki_plugin = 0 ]; then
  ynh_replace_string --match_string="__USE_WIKI_PLUGIN__" --replace_string="False" --target_file=$final_path/config/app_config.yml
else
  ynh_replace_string --match_string="__USE_WIKI_PLUGIN__" --replace_string="True" --target_file=$final_path/config/app_config.yml
fi

# Note(decentral1se): Handle YAML truthiness
if [ $use_messages_plugin = 0 ]; then
  ynh_replace_string --match_string="__USE_MESSAGES_PLUGIN__" --replace_string="False" --target_file=$final_path/config/app_config.yml
else
  ynh_replace_string --match_string="__USE_MESSAGES_PLUGIN__" --replace_string="True" --target_file=$final_path/config/app_config.yml
fi

ynh_replace_string --match_string="__NOTIFICATION_SENDER_EMAIL__" --replace_string=$notification_sender_email --target_file=$final_path/config/app_config.yml
ynh_replace_string --match_string="__NOTIFICATION_REPLY_EMAIL__" --replace_string=$notification_reply_email --target_file=$final_path/config/app_config.yml
ynh_replace_string --match_string="__ADMIN_EMAIL__" --replace_string=$admin_email --target_file=$final_path/config/app_config.yml
ynh_replace_string --match_string="__PORT__" --replace_string=$port --target_file=$final_path/config/app_config.yml

#=================================================
# INSTALL APPLICATION DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing Ruby $ruby_version dependencies..." --weight=50

gem_args="--no-rdoc --no-ri"

/opt/rbenv/versions/$ruby_version/bin/gem install $gem_args bundler -v "~> 1"
/opt/rbenv/versions/$ruby_version/bin/gem install $gem_args passenger -v "~> 6"

cd $final_path

/opt/rbenv/versions/$ruby_version/bin/bundle config build.nokogiri "--use-system-libraries"
/opt/rbenv/versions/$ruby_version/bin/bundle install --deployment --without development test -j 2

cd -

#=================================================
# RUN DATABASE SETUP AND MIGRATION WITH ROOT USER
#=================================================
ynh_script_progression --message="Initialising the database..." --weight=20

cp ../conf/db_setup.yml $final_path/config/database.yml

ynh_replace_string --match_string="__DB_NAME__" --replace_string=$db_name --target_file=$final_path/config/database.yml

cd $final_path

/opt/rbenv/versions/$ruby_version/bin/bundle exec rake db:setup RAILS_ENV=production SECRET_KEY_BASE=$secret_key_base

cd -

#=================================================
# RUN DATABASE MIGRATION WITH APPLICATION USER
#=================================================
ynh_script_progression --message="Migrating the database..." --weight=10

cp ../conf/db_prod.yml $final_path/config/database.yml

db_pwd=$(ynh_app_setting_get --app=$app --key=mysqlpwd)

ynh_replace_string --match_string="__DB_NAME__" --replace_string=$db_name --target_file=$final_path/config/database.yml
ynh_replace_string --match_string="__DB_PASSWORD__" --replace_string=$db_pwd --target_file=$final_path/config/database.yml
ynh_replace_string --match_string="__DB_USER__" --replace_string=$db_user --target_file=$final_path/config/database.yml

cd $final_path

/opt/rbenv/versions/$ruby_version/bin/bundle exec rake db:migrate RAILS_ENV=production SECRET_KEY_BASE=$secret_key_base

cd -

#=================================================
# SETUP ADMINSTRATOR ACCOUNT
#=================================================
ynh_script_progression --message="Setting up the adminstrator account..." --weight=4

root_pwd=$(sudo cat /etc/yunohost/mysql)

admin_first_name=$(ynh_user_get_info --username=$admin --key=firstname)
admin_last_name=$(ynh_user_get_info --username=$admin --key=lastname)
admin_email=$(ynh_user_get_info --username=$admin --key=mail)

# Note(decentral1se): figure out how to update the password and salt. Not sure which to use
# root@ynhdev-decentral1-se:~# mysql -u root -e "connect foodsoft; select * from users where nick = 'admin'"
# +----+--------------+------------------------------------------+--------------- ...
# | id | nick         | password_hash                            | password_salt  ...
# +----+--------------+------------------------------------------+--------------- ...
# |  1 | admin        | 7a2fe6291c632523300b8ab4ac70559ea0b706fa | g/6muzHs       ...
# +----+--------------+------------------------------------------+--------------- ...

ynh_mysql_execute_as_root --sql="update users set first_name = '$admin_first_name' where nick = 'admin';" --database=$app
ynh_mysql_execute_as_root --sql="update users set last_name = '$admin_last_name' where nick = 'admin';" --database=$app
ynh_mysql_execute_as_root --sql="update users set nick = '$admin' where nick = 'admin';" --database=$app

#=================================================
# PRE-COMPILE ASSETS
#=================================================
ynh_script_progression --message="Pre-compiling application assets..." --weight=40

cd $final_path

/opt/rbenv/versions/$ruby_version/bin/bundle exec rake assets:precompile RAILS_ENV=production SECRET_KEY_BASE=$secret_key_base

cd -

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring nginx web server..." --weight=1

ynh_add_nginx_config

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression --message="Configuring system user..." --weight=3

ynh_system_user_create --username=$app --home_dir=/home/$app

#=================================================
# MANAGE PERMISSIONS
#=================================================
ynh_script_progression --message="Securing permissions..." --weight=1

chown -R $app:$app $final_path

if [ $is_public -eq 0 ]
then
  ynh_app_setting_delete --app=$app --key=skipped_uris
fi

#=================================================
# SETUP SYSTEMD BASED SERVICES
#=================================================
ynh_script_progression --message="Configuring the systemd services..." --weight=1

ynh_add_systemd_config --service=foodsoft --template=foodsoft.service

ynh_replace_string --match_string="__RUBY_VERSION__" --replace_string=$ruby_version --target_file=/etc/systemd/system/foodsoft.service
ynh_replace_string --match_string="__PORT__" --replace_string=$port --target_file=/etc/systemd/system/foodsoft.service

queue_name=$app
smtp_domain=$smtp_domain
smtp_address=$app@$smtp_domain
smtp_port=25
smtp_user_name=$app

# TODO(decentral1se): figure out what to do here
smtp_password=__TODO__

ynh_app_setting_set --app=$app --key=queue_name --value=$queue_name

cp ../conf/foodsoft.env /etc/systemd/system/foodsoft.env
ynh_replace_string --match_string="__REDIS_URL__" --replace_string="redis://localhost:6379" --target_file=/etc/systemd/system/foodsoft.env
ynh_replace_string --match_string="__SECRET_KEY_BASE__" --replace_string=$secret_key_base --target_file=/etc/systemd/system/foodsoft.env
ynh_replace_string --match_string="__QUEUE_NAME__" --replace_string=$queue_name --target_file=/etc/systemd/system/foodsoft.env
ynh_replace_string --match_string="__RUBY_VERSION__" --replace_string=$ruby_version --target_file=/etc/systemd/system/foodsoft.env
ynh_replace_string --match_string="__SMTP_DOMAIN__" --replace_string=$smtp_domain --target_file=/etc/systemd/system/foodsoft.env
ynh_replace_string --match_string="__SMTP_ADDRESS__" --replace_string=$smtp_address --target_file=/etc/systemd/system/foodsoft.env
ynh_replace_string --match_string="__SMTP_PORT__" --replace_string=$smtp_port --target_file=/etc/systemd/system/foodsoft.env
ynh_replace_string --match_string="__SMTP_USER_NAME__" --replace_string=$smtp_user_name --target_file=/etc/systemd/system/foodsoft.env
ynh_replace_string --match_string="__SMTP_PASSWORD__" --replace_string=$smtp_password --target_file=/etc/systemd/system/foodsoft.env

ynh_add_systemd_config --service=resque  --template=resque.service

ynh_replace_string --match_string="__RUBY_VERSION__" --replace_string=$ruby_version --target_file=/etc/systemd/system/resque.service
ynh_replace_string --match_string="__PORT__" --replace_string=$port --target_file=/etc/systemd/system/resque.service

cp ../conf/resque.env /etc/systemd/system/resque.env

ynh_replace_string --match_string="__QUEUE_NAME__" --replace_string=$queue_name --target_file=/etc/systemd/system/resque.env

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression --message="Configuring log rotation..." --weight=1

ynh_use_logrotate --logfile=$passenger_log_file

ynh_use_logrotate --logfile=$prod_log_file

#=================================================
# ADVERTISE SERVICE IN ADMIN PANEL
#=================================================
ynh_script_progression --message="Advertisting new services..." --weight=1

yunohost service add $app --description "$app daemon" --log $passenger_log_file

yunohost service add resque --description "resque daemon" --log $prod_log_file

#=================================================
# START SYSTEMD SERVICE
#=================================================

ynh_script_progression --message="Starting the systemd services..." --weight=5

ynh_systemd_action --service_name=foodsoft --action="enable"
ynh_systemd_action --service_name=foodsoft --action="start"

ynh_systemd_action --service_name=resque --action="enable"
ynh_systemd_action --service_name=resque --action="start"

#=================================================
# SETUP SSOWAT
#=================================================
ynh_script_progression --message="Configuring SSOwat..." --weight=1

if [ $is_public -eq 1 ]
then
  ynh_app_setting_set --app=$app --key=unprotected_uris --value="/"
fi

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading nginx web server..." --weight=1

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
